swagger: '2.0'
info:
  title: 次世代KOMTRAX API
  description: |
    # 変更履歴
    <table>
      <tr><th>日付</th><th>変更内容</th></tr>
      <tr>
        <td>2022/3/29</td>
        <td>作成</td>
      </tr>
    </table>
  version: ''
paths:
  #パス名（パスパラメータを用いる場合{xxx_id}を入れる）
  /cars/requests/customize_data/send_no/m2s (仮):
  #path_start
    #get|put|post|delete
    post: 
      # API名
      summary: カスタマイズデータ送信要求（送信番号指定）API [API_ID：KOM-0xxxxxxx]
      # API説明文
      description: |
        指定された未受信カスタマイズデータの送信番号を過去カスタマイズデータ再送要求バッチの処理対象に変更する。これにより、指定された送信番号は、カスタマイズデータ受信フローに入る。
        <h1>エラーコード一覧</h1>
        <!-- ない、もしくは未定の場合は見出し、表を削除 -->
        <ul>
          <li>API共通で返却されるエラーメッセージは<a href="https://miot-msd.jp.fujitsu.com/komtrax/resources/api/komtrax_docs/messages.html" target="_blank">KOMTRAX共通メッセージ</a>を参照</li>
          <style type="text/css">
            .kom_error_messages{
                background-color: #0001;
                height: auto;
                padding: 0;
              }
              .kom_error_messages table {
                width:100%;
                table-layout: fixed;
                word-wrap: break-word;
              }
              .kom_error_messages .kom_status {width: 7%}
              .kom_error_messages .kom_name {width: 20%}
              .kom_error_messages .kom_code {width: 10%}
              .kom_error_messages .kom_message {width: 30%}
              .kom_error_messages .kom_cause {width: 23%}
              .kom_error_messages .kom_remarks {width: 10%}
              .kom_error_bg{
                padding: 5px;
                border-radius: 2px;
              }
          </style>
          <li class="kom_error_bg"> エラー一覧
            <details>
              <div class="kom_error_messages">
                <table border=1>
                  <tr>
                    <th class="kom_status">HTTP<br>ステータス</th>
                    <th class="kom_name">項目名</th>
                    <th class="kom_code">エラーコード</th>
                    <th class="kom_message">出力メッセージ</th>
                    <th class="kom_cause">要因</th>
                    <th class="kom_remarks">備考</th>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>cars.customize_definitions.customize_definition_id</td>
                    <td>ACOM0153E</td>
                    <td>{{cars.customize_definitions.customize_definition_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                </table>
              </div>
            </details>
          </li>
        </ul>
        <h1>特記事項</h1>
        carsはmodel-type-rev-serialsの昇順でソートする。
        customize_definitionsはcustomize_definition_idの昇順でソートする。
        send_nosはその昇順でソートする。
      # リクエスト
      parameters:
        #共通のヘッダ
        - name: X-Lang
          in: header
          description: |
            論理名　　　：言語タグ<br>
            使用可能文字：半角英数字,ハイフンマイナス<br>
            桁／文字数　：2～35<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-AppCode
          in: header
          description: |
            論理名　　　：アプリコード<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-GroupId
          in: header
          description: |
            論理名　　　：グループID<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～19<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-DateFormat
          in: header
          description: |
            論理名　　　：日付形式<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-Fields
          in: header
          description: |
            論理名　　　：指定項目<br>
            使用可能文字：半角英数字,半角アンダーバー,半角ピリオド,半角カンマ<br>
            桁／文字数　：1～<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-ScreenCode
          in: header
          description: |
            論理名　　　：画面コード<br>
            使用可能文字：半角英数字,半角アンダーバー<br>
            桁／文字数　：1～64<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-WebApiKey
          in: header
          description: |
            論理名　　　：WebAPIキー<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：1～36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        #リクエストボディ
        - name: リクエストボディ
          in: body
          #ボディに何の情報が入るかを書く 例：登録情報
          description: |
            カスタマイズデータ送信要求（送信番号指定）条件。
          #必須項目かどうか true|false
          required: true 
          #bodyの中身
          schema:
            #以下にオブジェクトを参照、もしくは記入
            type: object
            required:
              - request_route_kind
              - cars
            properties:
              request_route_kind:
                type: string
                description: "要求経路区分"
                pattern: "半角数字"
                example: "0"
                enum:
                  - 0:指定なし
                  - 1:持込機器
              data_amount_upper_limit:
                type: string
                description: データ量上限（単位：KB）。
                minLength: 1
                maxLength: 10
                pattern: '数字'
                example: '1234567890'
              cars:
                type: array
                items:
                  type: object
                  description: 車両
                  required:
                    - model_type_rev_serial
                    - customize_definitions
                  properties:
                    model_type_rev_serial:
                      type: string
                      description: |
                        機種-型式(小変形含む)-機番。
                        *機種、型式(小変形含む)、機番をハイフンマイナス区切りで指定。ワイルドカード指定不可。
                      minLength: 1
                      maxLength: 57
                      pattern: '半角英数記号("、''、#、%、&、<、>、*以外)'
                      example: 'D85PX-15E0-A12345'
                    customize_definitions:
                      type: array
                      items:
                        type: object
                        description: カスタマイズ定義
                        required:
                          - customize_definition_id
                          - send_nos
                        properties:
                          customize_definition_id:
                            type: string
                            description: カスタマイズ定義ID
                            minLength: 1
                            maxLength: 19
                            pattern: '半角数字'
                            example: '1234567890123456789'
                          send_nos:
                            type: array
                            items:
                              type: string
                              description: 送信番号
                              minLength: 22
                              maxLength: 22
                              pattern: 半角英数字(YYYYMMDDThhmmssZFFFFFF固定)
                              example: 20170124T045040Z000001
      # タグはnamespaceとする
      tags:
        - cars
      # レスポンス
      responses:
        '200':
          #レスポンスについて簡単な説明（例：どんな情報を返すか）
          description: |
            処理された送信番号を返却する。
          schema:
            type: object
            properties:
              result_data:
                type: object
                properties:
                  cars:
                      type: array
                      items:
                        type: object
                        description: 車両
                        properties:
                          model_type_rev_serial:
                            type: string
                            description: |
                              機種-型式(小変形含む)-機番。
                              *機種、型式(小変形含む)、機番をハイフンマイナス区切りで指定。ワイルドカード指定不可。
                            minLength: 1
                            maxLength: 57
                            pattern: '半角英数記号("、''、#、%、&、<、>、*以外)'
                            example: 'D85PX-15E0-A12345'
                          customize_definitions:
                            type: array
                            items:
                              type: object
                              description: カスタマイズ定義
                              properties:
                                customize_definition_id:
                                  type: string
                                  description: カスタマイズ定義ID
                                  minLength: 1
                                  maxLength: 19
                                  pattern: '半角数字'
                                  example: '1234567890123456789'
                                send_nos:
                                  type: array
                                  items:
                                    type: string
                                    description: 送信番号
                                    minLength: 22
                                    maxLength: 22
                                    pattern: 半角英数字(YYYYMMDDThhmmssZFFFFFF固定)
                                    example: 20170124T045040Z000001
        #common_error
  #path_end
