swagger: '2.0'
info:
  title: 次世代KOMTRAX API
  description: |
    # 変更履歴
    <table>
      <tr><th>日付</th><th>変更内容</th></tr>
      <tr>
        <td>2022/3/30</td>
        <td>作成</td>
      </tr>
    </table>
  version: ''
paths:
  #パス名（パスパラメータを用いる場合{xxx_id}を入れる）
  /cars/requests/customize_settings_retry/s2m:
  #path_start
    #get|put|post|delete
    post: 
      # API名
      summary: 車両カスタマイズ設定要求再送API [API_ID：KOM-00110XXX]
      # API説明文
      description: |
        再送対象の車両カスタマイズ設定に対して再送要求をする。
        <h1>エラーコード一覧</h1>
        <!-- ない、もしくは未定の場合は見出し、表を削除 -->
        
        <ul>
          <li>API共通で返却されるエラーメッセージは<a href="https://miot-msd.jp.fujitsu.com/komtrax/resources/api/komtrax_docs/messages.html" target="_blank">KOMTRAX共通メッセージ</a>を参照</li>
          <style type="text/css">
            .kom_error_messages{
                background-color: #0001;
                height: auto;
                padding: 0;
              }
              .kom_error_messages table {
                width:100%;
                table-layout: fixed;
                word-wrap: break-word;
              }
              .kom_error_messages .kom_status {width: 7%}
              .kom_error_messages .kom_name {width: 20%}
              .kom_error_messages .kom_code {width: 10%}
              .kom_error_messages .kom_message {width: 30%}
              .kom_error_messages .kom_cause {width: 23%}
              .kom_error_messages .kom_remarks {width: 10%}
              .kom_error_bg{
                padding: 5px;
                border-radius: 2px;
              }
          </style>
          <li class="kom_error_bg"> エラー一覧
            <details>
              <div class="kom_error_messages">
                <table border=1>
                  <tr>
                    <th class="kom_status">HTTP<br>ステータス</th>
                    <th class="kom_name">項目名</th>
                    <th class="kom_code">エラーコード</th>
                    <th class="kom_message">出力メッセージ</th>
                    <th class="kom_cause">要因</th>
                    <th class="kom_remarks">備考</th>
                  </tr>
                  <tr>
                    <td>404</td>
                    <td>car_id</td>
                    <td>ACOM0248E</td>
                    <td>指定された車両は存在しません。</td>
                    <td>指定された車両IDの車両が存在しない、または参照する権限が無い場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_id</td>
                    <td>ACOM0108E</td>
                    <td>{{car_id}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_id</td>
                    <td>ACAR0173E</td>
                    <td>{{car_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_definition.customize_definition_id</td>
                    <td>ACOM0418E</td>
                    <td>指定されたカスタマイズ定義は存在しません。</td>
                    <td>指定されたカスタマイズ定義IDのカスタマイズ定義が存在しない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_definition.customize_definition_id</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_definition.customize_definition_id}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_definition.customize_definition_id</td>
                    <td>ACAR0173E</td>
                    <td>{{customize_usage_definition.customize_definition_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_definition.customize_definition_id</td>
                    <td></td>
                    <td>指定されたカスタマイズ定義は再送対象ではありません。</td>
                    <td>指定されたカスタマイズ定義IDのカスタマイズ定義が再送対象でない場合に返却されます。</td>
                    <td></td>
                  </tr>
                </table>
              </div>
            </details>
          </li>
        </ul>
        
        <h1>特記事項</h1>

      # リクエスト
      parameters:
        #共通のヘッダ
        - name: X-Lang
          in: header
          description: |
            論理名　　　：言語タグ<br>
            使用可能文字：半角英数字,ハイフンマイナス<br>
            桁／文字数　：2～35<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-AppCode
          in: header
          description: |
            論理名　　　：アプリコード<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-GroupId
          in: header
          description: |
            論理名　　　：グループID<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～19<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-DateFormat
          in: header
          description: |
            論理名　　　：日付形式<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-ScreenCode
          in: header
          description: |
            論理名　　　：画面コード<br>
            使用可能文字：半角英数字,半角アンダーバー<br>
            桁／文字数　：1～64<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-WebApiKey
          in: header
          description: |
            論理名　　　：WebAPIキー<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：1～36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        #リクエストボディ
        - name: リクエストボディ
          in: body
          #ボディに何の情報が入るかを書く 例：登録情報
          description: |
            車両カスタマイズ設定要求再送
          #必須項目かどうか true|false
          #bodyの中身
          schema:
            #以下にオブジェクトを参照、もしくは記入
            type: object
            title: REQUEST_BODY
            required:
              - "car_id"
              - "customize_definition"
            properties:
              car_id:
                type: string
                description: "車両ID"
                pattern: 半角数字
                minLength: 1
                maxLength: 19
                example: "1"
              customize_definition:
                type: array
                description: カスタマイズ定義
                items:
                  type: object
                  description: カスタマイズ定義
                  required:
                    - "customize_definition_id"
                  properties:
                    customize_definition_id:
                      type: string
                      description: カスタマイズ定義ID
                      minLength: 1
                      maxLength: 19
                      pattern: 半角数字
                      example: "1"
      # タグはnamespaceとする
      tags:
        - cars
      # レスポンス
      responses:
        '200':
          #レスポンスについて簡単な説明（例：どんな情報を返すか）
          description: | 
           リクエストキーを返却する。
          schema:
            type: object
            properties:
              result_data:
                type: object
                properties:
                  request_key:
                    type: string
                    description: リクエストキー（36進数文字列）
                    pattern: 半角英数字
                    maxLength: 10
                    minLength: 1
                    example: ffa112ba1d
        #common_error
  #path_end
