swagger: '2.0'
info:
  title: 次世代KOMTRAX API
  description: |
    # 変更履歴
    <table>
      <tr><th>日付</th><th>変更内容</th></tr>
      <tr>
        <td>2022/3/28</td>
        <td>作成</td>
      </tr>
    </table>
  version: ''
paths:
  #パス名（パスパラメータを用いる場合{xxx_id}を入れる）
  /cars/requests/customize_usage_definitions/s2m:
  #path_start
    #get|put|post|delete
    post: 
      # API名
      summary: 車両カスタマイズ用途定義更新要求API [API_ID：KOM-00110130]
      # API説明文
      description: |
        車両に紐づくカスタマイズ用途定義の更新を車両に要求する。
        <h1>エラーコード一覧</h1>
        <!-- ない、もしくは未定の場合は見出し、表を削除 -->
        
        <ul>
          <li>API共通で返却されるエラーメッセージは<a href="https://miot-msd.jp.fujitsu.com/komtrax/resources/api/komtrax_docs/messages.html" target="_blank">KOMTRAX共通メッセージ</a>を参照</li>
          <style type="text/css">
            .kom_error_messages{
                background-color: #0001;
                height: auto;
                padding: 0;
              }
              .kom_error_messages table {
                width:100%;
                table-layout: fixed;
                word-wrap: break-word;
              }
              .kom_error_messages .kom_status {width: 7%}
              .kom_error_messages .kom_name {width: 20%}
              .kom_error_messages .kom_code {width: 10%}
              .kom_error_messages .kom_message {width: 30%}
              .kom_error_messages .kom_cause {width: 23%}
              .kom_error_messages .kom_remarks {width: 10%}
              .kom_error_bg{
                padding: 5px;
                border-radius: 2px;
              }
          </style>
          <li class="kom_error_bg"> エラー一覧
            <details>
              <div class="kom_error_messages">
                <table border=1>
                  <tr>
                    <th class="kom_status">HTTP<br>ステータス</th>
                    <th class="kom_name">項目名</th>
                    <th class="kom_code">エラーコード</th>
                    <th class="kom_message">出力メッセージ</th>
                    <th class="kom_cause">要因</th>
                    <th class="kom_remarks">備考</th>
                  </tr>
                  <tr>
                    <td>404</td>
                    <td>car_id</td>
                    <td>ACOM0248E</td>
                    <td>指定された車両は存在しません。</td>
                    <td>指定された車両IDの車両が存在しない、または参照する権限が無い場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_id</td>
                    <td>ACOM0108E</td>
                    <td>{{car_id}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_id</td>
                    <td>ACAR0173E</td>
                    <td>{{car_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>request_route_kind</td>
                    <td>ACOM0108E</td>
                    <td>{{request_route_kind}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>request_route_kind</td>
                    <td>ACOM0163E</td>
                    <td>{{request_route_kind}}に指定された値は利用できません。</td>
                    <td>要求経路区分に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>instant_kind</td>
                    <td>ACOM0163E</td>
                    <td>{{instant_kind}}に指定された値は利用できません。</td>
                    <td>即時反映に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>continuous_kind</td>
                    <td>ACOM0163E</td>
                    <td>{{continuous_kind}}に指定された値は利用できません。</td>
                    <td>継続有無に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>instant_kind<br/>continuous_kind</td>
                    <td></td>
                    <td>{{instant_kind}}に即時が指定された場合、{{continuous_kind}}の入力は必須です。</td>
                    <td>即時反映に即時を指定かつ継続有無が未指定の場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.customize_usage_definition_id</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.customize_usage_definition_id}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.customize_usage_definition_id</td>
                    <td>ACAR0173E</td>
                    <td>{{customize_usage_definition.customize_usage_definition_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.version</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.version}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>            
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.request_kind</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.request_kind}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.request_kind</td>
                    <td>ACOM0163E</td>
                    <td>{{customize_usage_definition.request_kind}}に指定された値は利用できません。</td>
                    <td>実施内容に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.priority</td>
                    <td>ACOM0163E</td>
                    <td>{{customize_usage_definition.priority}}に指定された値は利用できません。</td>
                    <td>優先度に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_to</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.date_to}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_to</td>
                    <td>ACAR0152E</td>
                    <td>日付は'YYYY-MM-DD'の形式で入力してください。</td>
                    <td>指定された日付の形式が不正な場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_from</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.date_from}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_from</td>
                    <td>ACAR0152E</td>
                    <td>日付は'YYYY-MM-DD'の形式で入力してください。</td>
                    <td>指定された日付の形式が不正な場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_from</td>
                    <td>ACAR0174E</td>
                    <td>{{customize_usage_definition.date_from}}[{開始日}]は明日以降の日付を指定してください。</td>
                    <td>指定された開始日がAPI実行日以前の場合に返却されます。</td>
                    <td>{開始日}には、指定された開始日(customize_usage_definition.date_from)が表示されます。</td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.active_kind</td>
                    <td>ACOM0418E</td>
                    <td>{{customize_usage_definition.active_kind}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.active_kind</td>
                    <td>ACOM0163E</td>
                    <td>{{customize_usage_definition.active_kind}}に指定された値は利用できません。</td>
                    <td>有効・無効に指定できない値が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>customize_usage_definition.date_to</br>
                    customize_usage_definition.date_from
                    </td>
                    <td>ACOM0169E</td>
                    <td>{{customize_usage_definition.date_to}}は{{customize_usage_definition.date_from}}以降の日付で入力してください。</td>
                    <td>期間指定の終了日付が開始日付以降ではない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>instant_kind</br>
                    customize_usage_definition.request_kind
                    </td>
                    <td></td>
                    <td>{{instant_kind}}に即時が指定された場合、{{customize_usage_definition.request_kind}}に削除は指定できません。</td>
                    <td>即時反映に即時を指定かつ実施内容に削除が指定された場合に返却されます。</td>
                    <td></td>
                  </tr>
                </table>
              </div>
            </details>
          </li>
        </ul>
        
        <h1>特記事項</h1>
        継続有無は即時反映が1:即時の場合必須とする。

      # リクエスト
      parameters:
        #共通のヘッダ
        - name: X-Lang
          in: header
          description: |
            論理名　　　：言語タグ<br>
            使用可能文字：半角英数字,ハイフンマイナス<br>
            桁／文字数　：2～35<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-AppCode
          in: header
          description: |
            論理名　　　：アプリコード<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-GroupId
          in: header
          description: |
            論理名　　　：グループID<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～19<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-DateFormat
          in: header
          description: |
            論理名　　　：日付形式<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-ScreenCode
          in: header
          description: |
            論理名　　　：画面コード<br>
            使用可能文字：半角英数字,半角アンダーバー<br>
            桁／文字数　：1～64<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-WebApiKey
          in: header
          description: |
            論理名　　　：WebAPIキー<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：1～36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        #リクエストボディ
        - name: リクエストボディ
          in: body
          #ボディに何の情報が入るかを書く 例：登録情報
          description: |
            車両カスタマイズ用途定義更新要求
          #必須項目かどうか true|false
          #bodyの中身
          schema:
            #以下にオブジェクトを参照、もしくは記入
            type: object
            title: REQUEST_BODY
            required:
              - "car_id"
              - "request_route_kind"
            properties:
              car_id:
                type: string
                description: 車両ID
                pattern: 半角数字
                minLength: 1
                maxLength: 19
                example: "1"
              request_route_kind:
                type: string
                description: 要求経路区分
                pattern: 半角数字
                maxLength: 1
                minLength: 1
                enum:
                  - 0:指定なし
                  - 1:持込機器
                example: "1"
              instant_kind:
                type: string
                description: 即時反映（未指定時は 0:通常 が適用される）
                pattern: 半角数字
                maxLength: 1
                minLength: 1
                enum:
                  - 0:通常
                  - 1:即時
                example: "1"
              continuous_kind:
                type: string
                description: 継続有無（即時反映が 1:即時 の場合必須）
                pattern: 半角数字
                maxLength: 1
                minLength: 1
                enum:
                  - 0:継続有り
                  - 1:継続無し
                example: "1"
              customize_usage_definition:
                type: array
                description: カスタマイズ用途定義
                items:
                  type: object
                  description: カスタマイズ用途定義
                  required:
                    - "customize_usage_definition_id"
                    - "version"
                    - "request_kind"
                    - "date_to"
                    - "date_from"
                    - "active_kind"
                  properties:
                    customize_usage_definition_id:
                      type: string
                      description: カスタマイズ用途定義ID
                      minLength: 1
                      maxLength: 19
                      pattern: 半角数字
                      example: "1"
                    version:
                      type: string
                      description: バージョン
                      pattern: 数値(小数部2桁)
                      maxLength: 5
                      minLength: 3
                      example: "20.13"
                    request_kind:
                      type: string
                      description: 実施内容
                      pattern: 半角数字
                      maxLength: 1
                      minLength: 1
                      example: "0"
                      enum:
                        - 0:追加
                        - 1:削除
                        - 2:更新
                    priority:
                      type: string
                      description: 優先度（未指定時は 0:low が適用される）
                      pattern: 半角数字
                      maxLength: 1
                      minLength: 1
                      example: "1"
                      enum:
                        - 0:low
                        - 1:middle
                        - 2:high
                    date_to:
                      type: string
                      description: 終了日
                      pattern: 日付(YYYY-MM-DD固定)
                      maxLength: 10
                      minLength: 10
                      example: "2017-12-31"
                    date_from:
                      type: string
                      description: 開始日
                      pattern: 日付(YYYY-MM-DD固定)
                      maxLength: 10
                      minLength: 10
                      example: "2017-12-30"
                    active_kind:
                      type: string
                      description: 有効・無効
                      pattern: 半角数字
                      maxLength: 1
                      minLength: 1
                      example: "1"
                      enum:
                        - 0:無効
                        - 1:有効
      # タグはnamespaceとする
      tags:
        - cars
      # レスポンス
      responses:
        '200':
          #レスポンスについて簡単な説明（例：どんな情報を返すか）
          description: | 
           リクエストキーを返却する。
          schema:
            type: object
            properties:
              result_data:
                type: object
                properties:
                  request_key:
                    type: string
                    description: リクエストキー（36進数文字列）
                    pattern: 半角英数字
                    maxLength: 10
                    minLength: 1
                    example: ffa112ba1d
        #common_error
  #path_end
