swagger: '2.0'
info:
  title: 次世代KOMTRAX API
  description: |
    # 変更履歴
    <table>
      <tr><th>日付</th><th>変更内容</th></tr>
      <tr>
        <td>2022/3/29</td>
        <td>作成</td>
      </tr>
    </table>
  version: ''
paths:
  #パス名（パスパラメータを用いる場合{xxx_id}を入れる）
  /cars/request_sets/customize_usage_definitions/m2s:
  #path_start
    #get|put|post|delete
    post: 
      # API名
      summary: 車両カスタマイズ用途定義一括取得要求API [API_ID：KOM-00110120]
      # API説明文
      description: |
        複数車両毎に車両に紐づくカスタマイズ用途定義の一括取得を車両に要求する。
        <h1>エラーコード一覧</h1>
        <!-- ない、もしくは未定の場合は見出し、表を削除 -->
        
        <ul>
          <li>API共通で返却されるエラーメッセージは<a href="https://miot-msd.jp.fujitsu.com/komtrax/resources/api/komtrax_docs/messages.html" target="_blank">KOMTRAX共通メッセージ</a>を参照</li>
          <style type="text/css">
            .kom_error_messages{
                background-color: #0001;
                height: auto;
                padding: 0;
              }
              .kom_error_messages table {
                width:100%;
                table-layout: fixed;
                word-wrap: break-word;
              }
              .kom_error_messages .kom_status {width: 7%}
              .kom_error_messages .kom_name {width: 20%}
              .kom_error_messages .kom_code {width: 10%}
              .kom_error_messages .kom_message {width: 30%}
              .kom_error_messages .kom_cause {width: 23%}
              .kom_error_messages .kom_remarks {width: 10%}
              .kom_error_bg{
                padding: 5px;
                border-radius: 2px;
              }
          </style>
          <li class="kom_error_bg"> エラー一覧
            <details>
              <div class="kom_error_messages">
                <table border=1>
                  <tr>
                    <th class="kom_status">HTTP<br>ステータス</th>
                    <th class="kom_name">項目名</th>
                    <th class="kom_code">エラーコード</th>
                    <th class="kom_message">出力メッセージ</th>
                    <th class="kom_cause">要因</th>
                    <th class="kom_remarks">備考</th>
                  </tr>
                  <tr>
                    <td>404</td>
                    <td>car_ids</td>
                    <td>ACOM0248E</td>
                    <td>指定された車両は存在しません。</td>
                    <td>指定された車両IDの車両が存在しない、または参照する権限が無い場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_ids</td>
                    <td>ACOM0108E</td>
                    <td>{{car_id}}の入力は必須です。</td>
                    <td>入力必須項目が存在しない、または、存在しても値が指定されていない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>car_ids</td>
                    <td>ACAR0173E</td>
                    <td>{{car_id}}は1～19桁の半角数字で入力してください。</td>
                    <td>ID項目に1～19桁の半角数字以外が入力された場合に返却されます。</td>
                    <td></td>
                  </tr>
                </table>
              </div>
            </details>
          </li>
        </ul>
        
        <h1>特記事項</h1>

      # リクエスト
      parameters:
        #共通のヘッダ
        - name: X-Lang
          in: header
          description: |
            論理名　　　：言語タグ<br>
            使用可能文字：半角英数字,ハイフンマイナス<br>
            桁／文字数　：2～35<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-AppCode
          in: header
          description: |
            論理名　　　：アプリコード<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-GroupId
          in: header
          description: |
            論理名　　　：グループID<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～19<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-DateFormat
          in: header
          description: |
            論理名　　　：日付形式<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-ScreenCode
          in: header
          description: |
            論理名　　　：画面コード<br>
            使用可能文字：半角英数字,半角アンダーバー<br>
            桁／文字数　：1～64<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-WebApiKey
          in: header
          description: |
            論理名　　　：WebAPIキー<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：1～36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        #リクエストボディ
        - name: リクエストボディ
          in: body
          #ボディに何の情報が入るかを書く 例：登録情報
          description: |
            車両カスタマイズ用途定義一括取得要求
          #必須項目かどうか true|false
          #bodyの中身
          schema:
            #以下にオブジェクトを参照、もしくは記入
            type: object
            title: REQUEST_BODY
            required:
              - "cars"
            properties:
              cars:
                type: array
                description: 車両リスト
                items:
                  type: object
                  description: 車両
                  required:
                    - "car_id"
                    - "request_route_kind"
                  properties:
                    car_id:
                      type: string
                      description: 車両ID
                      pattern: 半角数字
                      minLength: 1
                      maxLength: 19
                      example: "1"
                    request_route_kind:
                      type: string
                      description: 要求経路区分
                      minLength: 1
                      maxLength: 1
                      example: "0"
                      enum:
                        - 0:指定なし
                        - 1:持込機器
      # タグはnamespaceとする
      tags:
        - cars
      # レスポンス
      responses:
        '200':
          #レスポンスについて簡単な説明（例：どんな情報を返すか）
          description: | 
           複数のリクエストキーを返却する。
          schema:
            type: object
            properties:
              result_data:
                type: object
                properties:
                  request_keys:
                    type: array
                    items:
                      type: string
                      description: リクエストキー（36進数文字列）
                      pattern: 半角英数字
                      maxLength: 10
                      minLength: 1
                      example: ffa112ba1d
        #common_error
  #path_end
