swagger: '2.0'
info:
  title: 次世代KOMTRAX API
  description: |
    # 変更履歴
    <table>
      <tr><th>日付</th><th>変更内容</th></tr>
      <tr>
        <td>-</td>
        <td>作成</td>
      </tr>
    </table>
  version: ""
paths:
  #パス名（パスパラメータを用いる場合{xxx_id}を入れる）
  /cars/{car_id}/car_customize_data_performance:
  #path_start
    #get|put|post|delete
    get: 
      # API名
      summary: 車両送信番号一覧取得API [API-ID：KOM-00110061]
      # API説明文
      description: |
        車両送信番号の一覧を取得する。
        <h1>エラーコード一覧</h1>
        <!-- ない、もしくは未定の場合は見出し、表を削除 -->
        
        <ul>
          <li>API共通で返却されるエラーメッセージは<a href="https://miot-msd.jp.fujitsu.com/komtrax/resources/api/komtrax_docs/messages.html" target="_blank">KOMTRAX共通メッセージ</a>を参照</li>
          <style type="text/css">
            .kom_error_messages{
                background-color: #0001;
                height: auto;
                padding: 0;
              }
              .kom_error_messages table {
                width:100%;
                table-layout: fixed;
                word-wrap: break-word;
              }
              .kom_error_messages .kom_status {width: 7%}
              .kom_error_messages .kom_name {width: 20%}
              .kom_error_messages .kom_code {width: 10%}
              .kom_error_messages .kom_message {width: 30%}
              .kom_error_messages .kom_cause {width: 23%}
              .kom_error_messages .kom_remarks {width: 10%}
              .kom_error_bg{
                padding: 5px;
                border-radius: 2px;
              }
          </style>
          <li class="kom_error_bg"> エラー一覧
            <details>
              <div class="kom_error_messages">
                <table border=1>
                  <tr>
                    <th class="kom_status">HTTP<br>ステータス</th>
                    <th class="kom_name">項目名</th>
                    <th class="kom_code">エラーコード</th>
                    <th class="kom_message">出力メッセージ</th>
                    <th class="kom_cause">要因</th>
                    <th class="kom_remarks">備考</th>
                  </tr>        
                   <tr>
                    <td>400</td>
                    <td>car_id</td>
                    <td>ACOM0362E</td>
                    <td>指定された{car_id}は存在しません。</td>
                    <td>該当の車両IDの車両が存在しない、または参照する権限が無い場合に返却されます。</td>
                    <td></td>
                  </tr>
                   <tr>
                    <td>400</td>
                    <td>customize_definition_id</td>
                    <td>ACAR0043E</td>
                    <td>指定された{customize_definition_id}は存在しません。</td>
                    <td>利用可能なカスタマイズ定義が存在しない場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>date_from</td>
                    <td>ACOM0169E</td>
                    <td>{date_from}[{0}]は本日以降の日付を指定してください。</td>
                    <td>指定された終了日がAPI実行日より過去の日付の場合に返却されます。</td>
                    <td></td>
                  </tr>
                  <tr>
                    <td>400</td>
                    <td>date_to</td>
                    <td>ACOM0169E</td>
                    <td>{date_to}は{{keys[1]}}以降の日付で入力してください。</td>
                    <td>期間指定の終了日付が開始日付以降ではない場合に返却されます。</td>
                    <td></td>
                  </tr>
                </table>
              </div>
            </details>
          </li>
        </ul>
        <h1>特記事項</h1>
        X-Sortヘッダに指定可能なソートキーを以下に列挙する。<br>
        <ul>
          <li>car_customized_definition.car_customize_data_performances.send_no</li>
          <li>car_customized_definition.car_customize_data_performances.status</li>
          <li>car_customized_definition.car_customize_data_performances.server_registration_time</li>
          <li>car_customized_definition.car_customize_data_performances.car_data_creation_time</li>
        </ul>
        未指定時のデフォルトソートは"car_customized_definition"内は第一ソートを"car_customized_definition.customize_definition_category_id"の昇順、
        第二ソートを"car_customized_definition.car_customize_data_performances.send_no"の昇順でソートする。<br>

      # リクエスト
      parameters:
        #共通のヘッダ
        - name: X-Lang
          in: header
          description: |
            論理名　　　：言語タグ<br>
            使用可能文字：半角英数字,ハイフンマイナス<br>
            桁／文字数　：2～35<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-AppCode
          in: header
          description: |
            論理名　　　：アプリコード<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-GroupId
          in: header
          description: |
            論理名　　　：グループID<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～19<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-DateFormat
          in: header
          description: |
            論理名　　　：日付形式<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-ScreenCode
          in: header
          description: |
            論理名　　　：画面コード<br>
            使用可能文字：半角英数字,半角アンダーバー<br>
            桁／文字数　：1～64<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-WebApiKey
          in: header
          description: |
            論理名　　　：WebAPIキー<br>
            使用可能文字：半角英数記号<br>
            桁／文字数　：1～36<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
        - name: X-From
          in: header
          description: |
            論理名　　　：取得開始位置<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: number
        - name: X-Count
          in: header
          description: |
            論理名　　　：取得件数<br>
            使用可能文字：半角数字<br>
            桁／文字数　：1～<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: number
        - name: X-Sort
          in: header
          description: |
            論理名　　　：ソート<br>
            使用可能文字：半角英数字,ハイフンマイナス,半角アンダーバー,半角ピリオド,半角カンマ,半角コロン<br>
            桁／文字数　：1～<br>
            備考　　　　：詳細はAPI設計ポリシーを参照
          required: false
          type: string
          #車両ID
        - name: car_id
          in: path
          description: |
            論理名　　　：車両ID
            使用可能文字：半角数字
            桁／文字数　：1～19
            備考　　　　：完全一致
          required: true 
          type: string
          #カスタマイズ定義ID
        - name: customize_definition_id
          in: query
          description: |
            論理名　　　：カスタマイズ定義カテゴリID
            使用可能文字：半角数字
            桁／文字数　：1～19
            備考　　　　：完全一致
          required: true 
          type: string
          #対象期間開始年月日
        - name: date_from
          in: query
          description: |
            論理名　　　：対象期間開始年月日
            使用可能文字：日付(YYYY-MM-DD固定)
            桁／文字数　：10
            備考　　　　：未指定時は、対象期間終了年月日以前を取得。
            　　　　　　　date_from、date_to両方未指定時は、全期間を取得。
          required: false 
          type: string
          #対象期間終了年月日
        - name: date_to
          in: query
          description: |
            論理名　　　：対象期間終了年月日
            使用可能文字：日付(YYYY-MM-DD固定)
            桁／文字数　：10
            備考　　　　：未指定時は、対象期間開始年月日以降を取得。
            　　　　　　　date_from、date_to両方未指定時は、全期間を取得。
          required: false 
          type: string
      # タグはnamespaceとする
      tags:
        - cars
      # レスポンス
      responses:
        '200':
          description: "車両送信番号情報を返却する。"
          schema:
            type: object
            properties:
              result_data:
                $ref: '#/definitions/result_data'
        #common_error
  #path_end
definitions:        
  car_customized_definition:
    type: object
    properties:
        customize_definition_category_id:
          type: integer
          description: "カスタマイズ定義カテゴリID"
          example: 1
        customize_definition_version: 
          type: string
          description: "カスタマイズ定義バージョン"
          example:  "1.2" 
        customize_definition_name: 
          type: string
          description: "カスタマイズ定義名称"
          example:  "アプリUDO"
        assumption_data_value:
          type: string
          description: "想定データ量"
          example:  "XXXX" 
        car_customize_data_performances:
          $ref: '#/definitions/car_customize_data_performances'

  car_customize_data_performances:
      type: object
      properties:
        send_no:
          type: string
          description: "送信番号"
          example: "20200619T091709Z002002"
        status: 
          type: string
          description: "ステータス"
          example:  "未受信" 
        status_name: 
          type: string
          description: "ステータス名"
          example:  "未受信" 
        customized_data_achievement_details:
           $ref: '#/definitions/customized_data_achievement_details'

  customized_data_achievement_details:
      type: object
      properties:
          server_registration_time:
            type: string
            description: "サーバー登録日時"
            example: "2022-04-05 09:18:24"
          car_data_creation_time: 
            type: string
            description: "車両データ生成日時"
            example:  "2022-04-05 22:13:59" 

  result_data:
    type: object
    required:
      - id
      - name
      - send_date_to
      - request_api_id
      - result_api_id
      - status_code
      - status_name
    description: ""
    properties:
      car_customized_definition:
        $ref: '#/definitions/car_customized_definition'
      
  
      
